# Importing PyTorch

In [1]:
import torch

In [2]:
pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.8/150.8 MB 12.2 MB/s  0:00:12m0:00:0100:01

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


# Creating Your First Tensor

In [3]:
import torch
tensor = torch.tensor([1, 2, 3, 4, 5])
print(tensor)


tensor([1, 2, 3, 4, 5])


# Performing Simple Tensor Operations

In [9]:
import torch
 
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
 
addition = x + y
multiplication = x * y
 
print("Addition:", addition)
print("Multiplication:", multiplication)


Addition: tensor([5, 7, 9])
Multiplication: tensor([ 4, 10, 18])


# Performing Matrix Operations

In [5]:
import torch
 
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])
 
result = torch.matmul(matrix1, matrix2)
 
print(result)


tensor([[19, 22],
        [43, 50]])


# Running Computation on GPU

In [6]:
import torch
 
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available")
else:
    device = torch.device("cpu")
    print("GPU is not available")
 
tensor = torch.tensor([1, 2, 3]).to(device)
 
print(tensor)


GPU is not available
tensor([1, 2, 3])


# What is a Tensor in PyTorch?

In [PyTorch](https://pytorch.org?utm_source=chatgpt.com), a **tensor** is the primary data structure used to store and process data.
A tensor is similar to a NumPy array but provides additional capabilities such as GPU acceleration and automatic differentiation, which are essential for deep learning.

PyTorch tensors are used to represent:

* numbers,
* vectors,
* matrices,
* images,
* and multi-dimensional datasets.

---

# Types of Tensors

A tensor can have different dimensions.

| Tensor Type               | Dimensions | Example             |
| ------------------------- | ---------- | ------------------- |
| Scalar                    | 0D         | `5`                 |
| Vector                    | 1D         | `[1, 2, 3]`         |
| Matrix                    | 2D         | `[[1,2],[3,4]]`     |
| Higher-Dimensional Tensor | 3D+        | Image or video data |

---

# Importing PyTorch

```python
import torch
```

---

# Creating a Scalar Tensor (0D Tensor)

```python
scalar_tensor = torch.tensor(5)

print(scalar_tensor)
print(scalar_tensor.shape)
```

### Output

```python
tensor(5)
torch.Size([])
```

---

# Creating a Vector Tensor (1D Tensor)

```python
vector_tensor = torch.tensor([1, 2, 3, 4])

print(vector_tensor)
print(vector_tensor.shape)
```

### Output

```python
tensor([1, 2, 3, 4])
torch.Size([4])
```

---

# Creating a Matrix Tensor (2D Tensor)

```python
matrix_tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix_tensor)
print(matrix_tensor.shape)
```

### Output

```python
tensor([[1, 2, 3],
        [4, 5, 6]])

torch.Size([2, 3])
```

---

# Performing Tensor Operations

PyTorch tensors support mathematical operations.

```python
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

addition = x + y
multiplication = x * y

print("Addition:", addition)
print("Multiplication:", multiplication)
```

### Output

```python
Addition: tensor([5., 7., 9.])
Multiplication: tensor([ 4., 10., 18.])
```

---

# Understanding Tensor Shape

The `shape` attribute shows the dimensions of a tensor.

```python
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x.shape)
```

### Output

```python
torch.Size([2, 3])
```

This means:

* 2 rows
* 3 columns

---

# Tensor Data Types

Every tensor has a data type (`dtype`).

```python
x = torch.tensor([1, 2, 3])

print(x.dtype)
```

### Output

```python
torch.int64
```

---

# Moving Tensors to GPU

PyTorch can move tensors to a GPU for faster computation.

```python
device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor([1, 2, 3]).to(device)

print(x)
print(device)
```

---

# Automatic Gradient Tracking

PyTorch tensors can automatically track gradients during neural network training.

```python
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

print(x)
```

### Output

```python
tensor([1., 2., 3.], requires_grad=True)
```

---

# Why Tensors Are Important in Deep Learning

Tensors are the foundation of deep learning in PyTorch because they:

* efficiently store large datasets,
* support GPU acceleration,
* enable automatic differentiation,
* and perform high-speed mathematical computations.

All neural network operations in PyTorch are built using tensors.

---

# Summary

A PyTorch tensor is:

* a multi-dimensional array,
* optimized for numerical computation,
* capable of running on CPUs and GPUs,
* and designed specifically for machine learning and deep learning applications.
