In [1]:
# Dropout Introduction Example

import torch
import torch.nn as nn

torch.manual_seed(0)

dropout = nn.Dropout(p=0.5)

x = torch.ones(10)

print("Original Input:")
print(x)

dropout.train()
output_train = dropout(x)

print("\nOutput During Training:")
print(output_train)

dropout.eval()
output_eval = dropout(x)

print("\nOutput During Evaluation:")
print(output_eval)

Original Input:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Output During Training:
tensor([2., 0., 0., 2., 2., 0., 0., 2., 2., 2.])

Output During Evaluation:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
