# Scalars, Vectors, and Matrices

In [2]:
import torch
vector = torch.tensor([1, 2, 3, 4])
print(vector)


tensor([1, 2, 3, 4])


In [11]:
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
 
print(matrix)


tensor([[1, 2, 3],
        [4, 5, 6]])


# Matrix Multiplication

In [4]:
A = torch.tensor([
    [1, 2],
    [3, 4]
])
 
B = torch.tensor([
    [5, 6],
    [7, 8]
])
 
result = torch.matmul(A, B)
 
print(result)


tensor([[19, 22],
        [43, 50]])


# Tensors in Deep Learning

In [5]:
tensor = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
 
print(tensor)
print(tensor.shape)


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


# Tensor Shapes and Dimensions

In [6]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
 
print(x.shape)


torch.Size([2, 3])


# Broadcasting Operations

In [7]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
 
y = torch.tensor([10, 20, 30])
 
result = x + y
 
print(result)


tensor([[11, 22, 33],
        [14, 25, 36]])


# Hands-On Tensor Operations in PyTorch

In [8]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])
 
 
print(x + y)
print(x * y)
print(torch.mean(x))
print(torch.sum(y))


tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(2.)
tensor(15.)


# Chain Rule

In [10]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2

y.backward()
print(x.grad)


tensor(4.)
